name: Create app Fake
on: 
  workflow_dispatch:
    inputs:
      repo:
        description: Repo URL
        required: true
      app:
        description: App Name
        required: true
      token:
        description: token
        required: true

env:
  GITHUB_ORG: guedes-spot
  RUNNER: stackspot-stacks-qa
  STK: stk-alpha
  DEBUG: true

jobs:
  create:
    name: Create
    runs-on: [self-hosted, linux, stackspot-stacks-qa]
    steps:
      - name: Checkout workflows repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: workflow_repo
      - name: Checkout the user repo
        id: checkout_user_repo
        uses:  ./workflow_repo/github-actions/clone-external-repo2
        with:
          github_org: ${{ env.GITHUB_ORG }}
          app_name: ${{ inputs.app }}
          path: user_repo
          token: ${{ inputs.token }}
          github_url: ${{ inputs.repo }}
      - name: test github.workspace
        run: echo ${{ github.workspace }}
